services:
  backend:
    build:
      context: ./backend
    entrypoint: ./entrypoint.sh
    container_name: books-backend
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./backend:/app

  db:
    image: postgres:13
    container_name: books-database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/static:/usr/share/nginx/html/static
      - ./backend/media:/usr/share/nginx/html/media
    depends_on:
      - backend
    container_name: books-nginx

volumes:
  postgres_data:
